NoFriendlyFire:
  FriendlyFireMsg:
    Show: true
    MsgFriendlyFire: Friendly Fire won't be tolerated!
  DamagedByMsg:
    Show: false
    MsgDamagedBy: is a bad teammate, watch your back!
  Teams:
    #You can add an infinite number of teams here
    #Colors: http://www.minecraftwiki.net/wiki/Formatting_codes
    #ยง0 and black both work, color: NONE to disable
    team1:
      color: NONE
    team2:
      color: NONE
    team3:
      color: NONE
    team4:
      color: NONE
    team5:
      color: NONE